### ISSUE TITLE
UnsupportedOperationException when deleting selected edit part

### ISSUE THREAD

**Issue by ptziegler** [eclipse-gef/gef-classic#616]
The getSelectedEditParts() method introduced with https://github.com/eclipse-gef/gef-classic/pull/578 returns an unmodifiable list, while its counterpart may return a mutable list.

See:

```
java.lang.UnsupportedOperationException: null
	at java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?]
	at java.util.ImmutableCollections$AbstractImmutableList.set(ImmutableCollections.java:262) ~[?:?]
	at de.dsa.authoring.client.richgui.editors.chart.general.parts.TestModuleEditPart.getCommand(TestModuleEditPart.java:94) ~[de.dsa.authoring.client.richgui.editors.chart.general/:?]
	at org.eclipse.gef.ui.actions.DeleteAction.lambda$0(DeleteAction.java:103) ~[org.eclipse.gef_3.20.0.202411121909.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at org.eclipse.gef.ui.actions.DeleteAction.createDeleteCommand(DeleteAction.java:103) ~[org.eclipse.gef_3.20.0.202411121909.jar:?]
	at org.eclipse.gef.ui.actions.DeleteAction.calculateEnabled(DeleteAction.java:80) ~[org.eclipse.gef_3.20.0.202411121909.jar:?]
	at org.eclipse.gef.ui.actions.WorkbenchPartAction.refresh(WorkbenchPartAction.java:132) ~[org.eclipse.gef_3.20.0.202411121909.jar:?]
	at org.eclipse.gef.ui.actions.SelectionAction.handleSelectionChanged(SelectionAction.java:103) ~[org.eclipse.gef_3.20.0.202411121909.jar:?]
	at org.eclipse.gef.ui.actions.SelectionAction.setSelection(SelectionAction.java:114) ~[org.eclipse.gef_3.20.0.202411121909.jar:?]
	at org.eclipse.gef.ui.actions.SelectionAction.update(SelectionAction.java:137) ~[org.eclipse.gef_3.20.0.202411121909.jar:?]
```

For context: In our edit part, we dynamically try to replace elements int the list of selected edit parts. Because the list of edit parts was mutable, this didn't cause any issues up until now.

**Comment by ptziegler** [comment]
The StructuredSelection is internally [implemented](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/StructuredSelection.java) via `Arrays.asList(...)`, which doesn't allow addition or deletion, but simple replacement.

https://github.com/eclipse-gef/gef-classic/blob/177668186b3c35c35e3e821dc6727a34a898ff1c/org.eclipse.gef/src/org/eclipse/gef/ui/actions/SelectionAction.java#L72-L77

**Comment by ptziegler** [comment]
Because the code was written ~10 years ago by people who are probably not that deep into GEF...In short: We have an EditPart within an EditPart, where the actual edit part that's deleted always needs to be the parent. The test is just a simplification of this.Generally I agree that an immutable list should be used. But now we're breaking existing (even if unintentional) behavior, which I think is always dangerous.On Nov 17, 2024 15:38, azoitl ***@***.***> wrote:
May I ask why you need to exchange selected EditParts? Because in general I would find it better if we can keep certain list inmutable.

**Comment by azoitl** [comment]
Ah, I expected something like this. We need to do this also in one of the 4diac IDE editors. However we luckily created a new list.
